controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix:
        en: ''
        fr: /{_locale}
        de: /{_locale}
        es: /{_locale}
        nl: /{_locale}
        it: /{_locale}

    defaults:
        _locale: 'fr' 
    requirements:
        _locale: 'fr|en|de|it|nl|es' 
